# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.7.0
_src_path: gh:algorandfoundation/algokit-python-template
author_email: m.matusiak@se22.qmul.ac.uk
author_name: Maksymilian Jan Matusiak
contract_name: hello_world
deployment_language: python
preset_name: starter
project_name: TokenForge-contracts

