# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.1.1
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: m.matusiak@se22.qmul.ac.uk
author_name: Maksymilian Jan Matusiak
preset_name: starter
project_name: TokenForge-frontend

